#!/bin/sh
# Generates the Vala bindings file 'emerillon.vapi' from introspection data (emerillon.gi).
# emerillon.gi can be generated by 'vala-gen-introspect emerillon emerillon'
vapigen --library emerillon --pkg champlain-0.10 --pkg gtk+-3.0 --pkg clutter-1.0 emerillon/emerillon.gi

